In [32]:
import numpy as np
import pandas as pd

**Import Dataset**

In [33]:
players = pd.read_csv("/content/afl_players_info_raw.csv")
stat = pd.read_csv("/content/afl_players_seasonal_stats_raw.csv")

/tmp/ipykernel_1164/626523569.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  stat = pd.read_csv("/content/afl_players_seasonal_stats_raw.csv")

**Players info**

In [34]:
print("Players information",players.shape)
print(players.info())
print(players.describe(include="all"),"\n")

Players information (2848, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2848 entries, 0 to 2847
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2848 non-null   int64
 1   player_name          2848 non-null   object
 2   player_full_name     2848 non-null   object
 3   first_name           2848 non-null   object
 4   last_name            2848 non-null   object
 5   born_date            2848 non-null   object
 6   debut_date           2848 non-null   object
 7   debut_age            2848 non-null   int64
 8   last_date            2848 non-null   object
 9   last_age             2848 non-null   int64
 10  height               2848 non-null   int64
 11  weight               2848 non-null   int64
 12  profile_pic          637 non-null    object
 13  player_link          2848 non-null   object
 14  player_common_names  75 non-null     object
 15  player_teams         2754 non-null   object
dtypes: int64(5), object(11)
memory usage: 356.1+ KB
None
                  id  player_name player_full_name first_name last_name  \
count    2848.000000         2848             2848       2848      2848
unique           NaN         2826             2843        742      1998
top              NaN  Aaron Black      Ryan_Abbott        Tom     Smith
freq             NaN            2                2         63        24
mean    44858.623947          NaN              NaN        NaN       NaN
std       912.449281          NaN              NaN        NaN       NaN
min     43260.000000          NaN              NaN        NaN       NaN
25%     44063.750000          NaN              NaN        NaN       NaN
50%     44885.500000          NaN              NaN        NaN       NaN
75%     45662.250000          NaN              NaN        NaN       NaN
max     46374.000000          NaN              NaN        NaN       NaN

         born_date  debut_date    debut_age   last_date     last_age  \
count         2848        2848  2848.000000        2848  2848.000000
unique        2546        1610          NaN        1305          NaN
top     1989-10-09  2012-03-24          NaN  2025-08-22          NaN
freq             4          15          NaN          67          NaN
mean           NaN         NaN    19.595857         NaN    25.765449
std            NaN         NaN     1.824956         NaN     4.339853
min            NaN         NaN    16.000000         NaN    18.000000
25%            NaN         NaN    18.000000         NaN    22.000000
50%            NaN         NaN    19.000000         NaN    25.000000
75%            NaN         NaN    20.000000         NaN    29.000000
max            NaN         NaN    29.000000         NaN    40.000000

             height       weight  \
count   2848.000000  2848.000000
unique          NaN          NaN
top             NaN          NaN
freq            NaN          NaN
mean     187.344803    86.012289
std        7.318328     8.923524
min      163.000000     0.000000
25%      182.000000    80.000000
50%      187.000000    85.000000
75%      192.000000    92.000000
max      211.000000   118.000000

                                              profile_pic  \
count                                                 637
unique                                                636
top     https://res.cloudinary.com/dijzdikkh/image/upl...
freq                                                    2
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                                              player_link player_common_names  \
count                                                2848                  75
unique                                               2843                  75
top     https://afltables.com/afl/stats/players/R/Ryan...           {Big Mac}
freq                                                    2                   1
mean                                                  NaN                 NaN
std                                                   NaN                 NaN
min                                                   NaN                 NaN
25%                                                   NaN                 NaN
50%                                                   NaN                 NaN
75%                                                   NaN                 NaN
max                                                   NaN                 NaN

              player_teams
count                 2754
unique                 309
top     {Essendon Bombers}
freq                   131
mean                   NaN
std                    NaN
min                    NaN
25%                    NaN
50%                    NaN
75%                    NaN
max                    NaN

**Seasonal_stat info**

In [35]:
print("Seasonal_stat information",stat.shape)
print(stat.info())
print(stat.describe(include="all"),"\n")

Seasonal_stat information (25491, 54)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25491 entries, 0 to 25490
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    25491 non-null  object
 1   year                         25491 non-null  int64
 2   team                         25491 non-null  object
 3   is_finals                    25491 non-null  bool
 4   games_played                 25491 non-null  int64
 5   kicks                        25439 non-null  float64
 6   marks                        25306 non-null  float64
 7   handballs                    25378 non-null  float64
 8   disposals                    25467 non-null  float64
 9   goals                        22954 non-null  float64
 10  behinds                      22802 non-null  float64
 11  hit_outs                     19785 non-null  float64
 12  tackles                      24980 non-null  float64
 13  rebound_50s                  21958 non-null  float64
 14  inside_50s                   22520 non-null  float64
 15  clearances                   22056 non-null  float64
 16  clangers                     22553 non-null  float64
 17  free_kicks_for               24418 non-null  float64
 18  free_kicks_against           24513 non-null  float64
 19  brownlow_votes               18494 non-null  float64
 20  contested_possessions        22155 non-null  float64
 21  uncontested_possessions      22169 non-null  float64
 22  contested_marks              20566 non-null  float64
 23  marks_inside_50              20326 non-null  float64
 24  one_percenters               21848 non-null  float64
 25  bounces                      19837 non-null  float64
 26  goal_assists                 18399 non-null  float64
 27  total_score                  25491 non-null  int64
 28  total_fantasy_points         25491 non-null  int64
 29  total_percentage_played      19245 non-null  float64
 30  avg_kicks                    25439 non-null  float64
 31  avg_marks                    25306 non-null  float64
 32  avg_handballs                25378 non-null  float64
 33  avg_disposals                25467 non-null  float64
 34  avg_goals                    22954 non-null  float64
 35  avg_behinds                  22802 non-null  float64
 36  avg_hit_outs                 19785 non-null  float64
 37  avg_tackles                  24980 non-null  float64
 38  avg_rebound_50s              21958 non-null  float64
 39  avg_inside_50s               22520 non-null  float64
 40  avg_clearances               22056 non-null  float64
 41  avg_clangers                 22553 non-null  float64
 42  avg_free_kicks_for           24418 non-null  float64
 43  avg_free_kicks_against       24513 non-null  float64
 44  avg_contested_possessions    22155 non-null  float64
 45  avg_uncontested_possessions  22169 non-null  float64
 46  avg_contested_marks          20566 non-null  float64
 47  avg_marks_inside_50          20326 non-null  float64
 48  avg_one_percenters           21848 non-null  float64
 49  avg_bounces                  19837 non-null  float64
 50  avg_goal_assists             18399 non-null  float64
 51  avg_score                    25491 non-null  float64
 52  avg_fantasy_points           25491 non-null  float64
 53  avg_percentage_played        19245 non-null  float64
dtypes: bool(1), float64(47), int64(4), object(2)
memory usage: 10.3+ MB
None
       player_id          year          team is_finals  games_played  \
count      25491  25491.000000         25491     25491  25491.000000
unique      3298           NaN           114         2           NaN
top        45522           NaN  Geelong Cats     False           NaN
freq          35           NaN          1263     19520           NaN
mean         NaN   2010.194500           NaN       NaN     10.748617
std          NaN      9.342562           NaN       NaN      7.832753
min          NaN   1983.000000           NaN       NaN    -21.000000
25%          NaN   2003.000000           NaN       NaN      3.000000
50%          NaN   2011.000000           NaN       NaN     10.000000
75%          NaN   2018.000000           NaN       NaN     19.000000
max          NaN   2025.000000           NaN       NaN     23.000000

               kicks         marks     handballs     disposals         goals  \
count   25439.000000  25306.000000  25378.000000  25467.000000  22954.000000
unique           NaN           NaN           NaN           NaN           NaN
top              NaN           NaN           NaN           NaN           NaN
freq             NaN           NaN           NaN           NaN           NaN
mean       98.697001     42.882281     67.689652    166.041583      7.169208
std        92.259369     39.119496     68.603571    154.153533     10.744221
min         0.000000      0.000000      0.000000      0.000000      0.000000
25%        20.000000      9.000000     13.000000     34.000000      1.000000
50%        66.000000     31.000000     44.000000    114.000000      3.000000
75%       161.000000     70.000000    103.000000    268.000000      9.000000
max       512.000000    226.000000    482.000000    787.000000    123.000000

        ...  avg_contested_possessions  avg_uncontested_possessions  \
count   ...               22155.000000                 22169.000000
unique  ...                        NaN                          NaN
top     ...                        NaN                          NaN
freq    ...                        NaN                          NaN
mean    ...                   5.429564                     8.575497
std     ...                   2.585986                     3.994015
min     ...                   0.000000                     0.000000
25%     ...                   3.800000                     5.600000
50%     ...                   5.000000                     8.000000
75%     ...                   6.600000                    11.100000
max     ...                  22.000000                    29.000000

        avg_contested_marks  avg_marks_inside_50  avg_one_percenters  \
count          20566.000000         20326.000000        21848.000000
unique                  NaN                  NaN                 NaN
top                     NaN                  NaN                 NaN
freq                    NaN                  NaN                 NaN
mean               0.683696             0.732692            2.102938
std                0.672074             0.821606            1.629118
min                0.000000             0.000000            0.000000
25%                0.100000             0.000000            1.000000
50%                0.500000             0.500000            1.700000
75%                1.000000             1.000000            2.600000
max                6.000000             8.000000           22.000000

         avg_bounces  avg_goal_assists     avg_score  avg_fantasy_points  \
count   19837.000000      18399.000000  25491.000000        25491.000000
unique           NaN               NaN           NaN                 NaN
top              NaN               NaN           NaN                 NaN
freq             NaN               NaN           NaN                 NaN
mean        0.665075          0.481434      3.591742           59.519850
std         0.893630          0.487706      4.326204           21.492939
min         0.000000          0.000000      0.000000           -6.000000
25%         0.000000          0.000000      0.400000           45.000000
50%         0.300000          0.300000      2.300000           58.700000
75%         1.000000          0.800000      5.200000           73.800000
max        13.000000          4.000000     59.000000          149.000000

        avg_percentage_played
count            19245.000000
unique                    NaN
top                       NaN
freq                      NaN
mean                77.742931
std                 14.190194
min                  0.000000
25%                 72.500000
50%                 80.400000
75%                 86.300000
max                100.000000

[11 rows x 54 columns]

**Checking missing values**

In [36]:
print("Players missing values:\n",players.isnull().sum())
print("\nSeasonal_stat missing values:\n",stat.isnull().sum())

Players missing values:
 id                        0
player_name               0
player_full_name          0
first_name                0
last_name                 0
born_date                 0
debut_date                0
debut_age                 0
last_date                 0
last_age                  0
height                    0
weight                    0
profile_pic            2211
player_link               0
player_common_names    2773
player_teams             94
dtype: int64

Seasonal_stat missing values:
 player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                            52
marks                           185
handballs                       113
disposals                        24
goals                          2537
behinds                        2689
hit_outs                       5706
tackles                         511
rebound_50s                    3533
inside_50s                     2971
clearances                     3435
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

**Handling players missing values**

In [37]:
players.drop(columns=["profile_pic"], inplace=True)
players["player_common_names"] = players["player_common_names"].fillna("Unknown")
players["player_teams"] = players["player_teams"].fillna("Unknown")

**Handling Seasonal_stat missing values**

In [38]:
numeric_columns = stat.select_dtypes(include="number").columns
exclude_columns = ["year"]
for col in numeric_columns:
    if col not in exclude_columns:
        if stat[col].isnull().sum() > 0:
            median_value = stat[col].median()
            stat[col] = stat[col].fillna(median_value)
            print(f"{col}: missing values filled with median = {median_value}")

kicks: missing values filled with median = 66.0
marks: missing values filled with median = 31.0
handballs: missing values filled with median = 44.0
disposals: missing values filled with median = 114.0
goals: missing values filled with median = 3.0
behinds: missing values filled with median = 3.0
hit_outs: missing values filled with median = 0.0
tackles: missing values filled with median = 17.0
rebound_50s: missing values filled with median = 8.0
inside_50s: missing values filled with median = 14.0
clearances: missing values filled with median = 7.0
clangers: missing values filled with median = 16.0
free_kicks_for: missing values filled with median = 7.0
free_kicks_against: missing values filled with median = 7.0
brownlow_votes: missing values filled with median = 0.0
contested_possessions: missing values filled with median = 43.0
uncontested_possessions: missing values filled with median = 66.0
contested_marks: missing values filled with median = 3.0
marks_inside_50: missing values filled with median = 2.0
one_percenters: missing values filled with median = 13.0
bounces: missing values filled with median = 2.0
goal_assists: missing values filled with median = 2.0
total_percentage_played: missing values filled with median = 723.0
avg_kicks: missing values filled with median = 8.0
avg_marks: missing values filled with median = 3.6
avg_handballs: missing values filled with median = 5.2
avg_disposals: missing values filled with median = 13.3
avg_goals: missing values filled with median = 0.7
avg_behinds: missing values filled with median = 0.5
avg_hit_outs: missing values filled with median = 0.0
avg_tackles: missing values filled with median = 2.2
avg_rebound_50s: missing values filled with median = 1.4
avg_inside_50s: missing values filled with median = 2.0
avg_clearances: missing values filled with median = 1.2
avg_clangers: missing values filled with median = 2.0
avg_free_kicks_for: missing values filled with median = 1.0
avg_free_kicks_against: missing values filled with median = 1.0
avg_contested_possessions: missing values filled with median = 5.0
avg_uncontested_possessions: missing values filled with median = 8.0
avg_contested_marks: missing values filled with median = 0.5
avg_marks_inside_50: missing values filled with median = 0.5
avg_one_percenters: missing values filled with median = 1.7
avg_bounces: missing values filled with median = 0.3
avg_goal_assists: missing values filled with median = 0.3
avg_percentage_played: missing values filled with median = 80.4

In [39]:
print("Players missing values:\n",players.isnull().sum())
print("\nSeasonal_stat missing values:\n",stat.isnull().sum())

Players missing values:
 id                     0
player_name            0
player_full_name       0
first_name             0
last_name              0
born_date              0
debut_date             0
debut_age              0
last_date              0
last_age               0
height                 0
weight                 0
player_link            0
player_common_names    0
player_teams           0
dtype: int64

Seasonal_stat missing values:
 player_id                      0
year                           0
team                           0
is_finals                      0
games_played                   0
kicks                          0
marks                          0
handballs                      0
disposals                      0
goals                          0
behinds                        0
hit_outs                       0
tackles                        0
rebound_50s                    0
inside_50s                     0
clearances                     0
clangers                       0
free_kicks_for                 0
free_kicks_against             0
brownlow_votes                 0
contested_possessions          0
uncontested_possessions        0
contested_marks                0
marks_inside_50                0
one_percenters                 0
bounces                        0
goal_assists                   0
total_score                    0
total_fantasy_points           0
total_percentage_played        0
avg_kicks                      0
avg_marks                      0
avg_handballs                  0
avg_disposals                  0
avg_goals                      0
avg_behinds                    0
avg_hit_outs                   0
avg_tackles                    0
avg_rebound_50s                0
avg_inside_50s                 0
avg_clearances                 0
avg_clangers                   0
avg_free_kicks_for             0
avg_free_kicks_against         0
avg_contested_possessions      0
avg_uncontested_possessions    0
avg_contested_marks            0
avg_marks_inside_50            0
avg_one_percenters             0
avg_bounces                    0
avg_goal_assists               0
avg_score                      0
avg_fantasy_points             0
avg_percentage_played          0
dtype: int64

**Checking and handling duplicate values**

In [40]:
print("Duplicate players:", players.duplicated().sum())
print("Duplicate stats:", stat.duplicated().sum())

Duplicate players: 5
Duplicate stats: 10

In [41]:
players = players.drop_duplicates()
stat = stat.drop_duplicates()

In [42]:
print("Duplicate players:", players.duplicated().sum())
print("Duplicate stats:", stat.duplicated().sum())

Duplicate players: 0
Duplicate stats: 0

# Cleaned Players Dataset

In [47]:
players.to_csv("/content/cleaned_players_info.csv",index=False)
print("\nCleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Cleaned Seasonal_stat Dataset

In [48]:
stat.to_csv("/content/cleaned_Seasonal_Stats.csv", index=False)
print("\nSeasonal Stats dataset saved successfully!")

Seasonal Stats dataset saved successfully!

**Cleaned datasets info**

In [50]:
print("CLEANED PLAYERS INFO")
print("Nulls:", players.isnull().sum().sum())
print("Duplicates:", players.duplicated().sum())

print("CLEANED SEASONAL STATS")
print("Nulls:", stat.isnull().sum().sum())
print("Duplicates:", stat.duplicated().sum())

CLEANED PLAYERS INFO
Nulls: 0
Duplicates: 0
CLEANED SEASONAL STATS
Nulls: 0
Duplicates: 0

# Merging cleaned datasets

In [51]:
players = players.rename(columns={"id": "player_id"})

# Merge cleaned datasets
merged_players = pd.merge(players,stat,on="player_id",how="inner")
# Check merged dataset
print("Merged Dataset Shape:", merged_players.shape)
display(merged_players.head())

merged_players.to_csv("/content/merged_players.csv",index=False)
print("Final dataset saved as: /content/merged_players.csv")

Merged Dataset Shape: (16027, 68)

,player_id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,80.4

Final dataset saved as: /content/merged_players.csv

**Final summary**

In [53]:
# Final Validation Report
validation_report = pd.DataFrame({"Dataset": ["Players","Stat","Merged Dataset"],
                                  "Duplicates Remaining": [players.duplicated().sum(),stat.duplicated().sum(),merged_players.duplicated().sum()],
                                  "Missing Values": [players.isnull().sum().sum(),stat.isnull().sum().sum(),merged_players.isnull().sum().sum()]})
# Display validation report
display(validation_report)

          Dataset  Duplicates Remaining  Missing Values
0         Players                     0               0
1            Stat                     0               0
2  Merged Dataset                     0               0